// <auto-generated />
using System;
using Centras.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Centras.Migrations
{
    [DbContext(typeof(CentrasContext))]
    [Migration("20250627083646_UpdatedDBWitRoomDescriptionsLT+Eng")]
    partial class UpdatedDBWitRoomDescriptionsLTEng
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Centras.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<string>("DescriptionEng")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionLT")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameLT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceForAdditionalBed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceForSecondPerson")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 5,
                            BasePrice = 55m,
                            Capacity = 0,
                            DescriptionEng = "\r\n                     Cozy room with a double bed and a view of the central city square with ringing bells and a splashing fountain.\r\n                     <ul>\r\n                         <li><i class='fas fa-wifi'></i> Free Wi-Fi</li>\r\n                         <li><i class='fas fa-utensils'></i> Breakfast available on-site</li>\r\n                         <li><i class='fas fa-snowflake'></i> Air conditioning</li>\r\n                         <li><i class='fas fa-car'></i> Free parking</li>\r\n                         <li><i class='fas fa-mug-hot'></i> Tea and coffee in the room</li>\r\n                         <li><i class='fas fa-shower'></i> Spacious bathroom with shower</li>\r\n                         <li><i class='fas fa-tv'></i> Television</li>\r\n                     </ul>\r\n                     <p><i class='fas fa-lock'></i> Safe for valuables available at the reception</p>",
                            DescriptionLT = "\r\n                    Jaukus kambarys su dvigule lova ir vaizdu į centrinę miesto aikštę su skambančiais varpais ir trykštančiu fontanu.\r\n                    <ul>\r\n                        <li><i class='fas fa-wifi'></i> Nemokamas Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Galimybė užsisakyti pusryčius vietoje</li>\r\n                        <li><i class='fas fa-snowflake'></i> Oro kondicionierius</li>\r\n                        <li><i class='fas fa-car'></i> Nemokama stovėjimo vieta</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Arbata ir kava kambaryje</li>\r\n                        <li><i class='fas fa-shower'></i> Erdvus vonios kambarys su dušu</li>\r\n                        <li><i class='fas fa-tv'></i> Televizorius</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Seifas vertingiems daiktams prieinamas registratūroje</p>",
                            NameEng = "Double Room",
                            NameLT = "Dvivietis Kambarys",
                            PriceForAdditionalBed = 15m,
                            PriceForSecondPerson = 10m
                        },
                        new
                        {
                            ID = 6,
                            BasePrice = 70m,
                            Capacity = 0,
                            DescriptionEng = "\r\n                    Spacious room with a classic interior and a view of the city square with ringing bells and a splashing fountain.\r\n                     <ul>\r\n                        <li><i class='fas fa-wifi'></i> Free Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Breakfast available on-site</li>\r\n                        <li><i class='fas fa-snowflake'></i> Air conditioning</li>\r\n                        <li><i class='fas fa-car'></i> Free parking</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Tea and coffee in the room</li>\r\n                        <li><i class='fas fa-shower'></i> Spacious bathroom with shower</li>\r\n                        <li><i class='fas fa-tv'></i> Television</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Safe for valuables available at the reception</p>",
                            DescriptionLT = "\r\n                    Erdvus kambarys su klasikiniu interjeru ir vaizdu į miesto aikštę su skambančiais varpais ir trykštančiu fontanu.\r\n                     <ul>\r\n                        <li><i class='fas fa-wifi'></i> Nemokamas Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Galimybė užsisakyti pusryčius vietoje</li>\r\n                        <li><i class='fas fa-snowflake'></i> Oro kondicionierius</li>\r\n                        <li><i class='fas fa-car'></i> Nemokama stovėjimo vieta</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Arbata ir kava kambaryje</li>\r\n                        <li><i class='fas fa-shower'></i> Erdvus vonios kambarys su dušu</li>\r\n                        <li><i class='fas fa-tv'></i> Televizorius</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Seifas vertingiems daiktams prieinamas registratūroje</p>",
                            NameEng = "Luxury Room",
                            NameLT = "Liukso Kambarys",
                            PriceForAdditionalBed = 15m,
                            PriceForSecondPerson = 10m
                        },
                        new
                        {
                            ID = 7,
                            BasePrice = 55m,
                            Capacity = 0,
                            DescriptionEng = "\r\n                    Comfortable and bright room with two single beds (double bed available on request).\r\n                    <ul>\r\n                        <li><i class='fas fa-wifi'></i> Free Wi-Fi</li>\r\n                        <li><i class='fas fa-snowflake'></i> Air conditioning</li>\r\n                        <li><i class='fas fa-utensils'></i> Breakfast available on-site</li>\r\n                        <li><i class='fas fa-car'></i> Free parking</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Tea and coffee in the room</li>\r\n                        <li><i class='fas fa-shower'></i> Spacious bathroom with shower</li>\r\n                        <li><i class='fas fa-tv'></i> Television</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Safe for valuables available at the reception</p>",
                            DescriptionLT = "\r\n                    Patogus ir šviesus kambarys su dviem viengulėmis lovomis (galima dvigulė lova).\r\n                    <ul>\r\n                        <li><i class='fas fa-wifi'></i> Nemokamas Wi-Fi</li>\r\n                        <li><i class='fas fa-snowflake'></i> Oro kondicionierius</li>\r\n                        <li><i class='fas fa-utensils'></i> Galimybė užsisakyti pusryčius vietoje</li>\r\n                        <li><i class='fas fa-car'></i> Nemokama stovėjimo vieta</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Arbata ir kava kambaryje</li>\r\n                        <li><i class='fas fa-shower'></i> Erdvus vonios kambarys su dušu</li>\r\n                        <li><i class='fas fa-tv'></i> Televizorius</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Seifas vertingiems daiktams prieinamas registratūroje</p>",
                            NameEng = "Twin Room (2 beds)",
                            NameLT = "Dvivietis Kambarys (2 lovos)",
                            PriceForAdditionalBed = 15m,
                            PriceForSecondPerson = 10m
                        },
                        new
                        {
                            ID = 8,
                            BasePrice = 70m,
                            Capacity = 0,
                            DescriptionEng = "\r\n                    Luxurious and spacious room with top-class amenities.\r\n                    <ul>\r\n                        <li><i class='fas fa-wifi'></i> Free Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Breakfast available on-site</li>\r\n                        <li><i class='fas fa-car'></i> Free parking</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Tea and coffee in the room</li>\r\n                        <li><i class='fas fa-shower'></i> Spacious bathroom with bathtub</li>\r\n                        <li><i class='fas fa-tv'></i> Television</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Safe for valuables available at the reception</p>",
                            DescriptionLT = "\r\n                    Prabangus ir erdvus kambarys ir aukščiausios klasės patogumais.\r\n                    <ul>\r\n                        <li><i class='fas fa-wifi'></i> Nemokamas Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Galimybė užsisakyti pusryčius vietoje</li>\r\n                        <li><i class='fas fa-car'></i> Nemokama stovėjimo vieta</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Arbata ir kava kambaryje</li>\r\n                        <li><i class='fas fa-shower'></i> Erdvus vonios kambarys su vonia</li>\r\n                        <li><i class='fas fa-tv'></i> Televizorius</li>\r\n                    </ul>\r\n                    <p><i class='fas fa-lock'></i> Seifas vertingiems daiktams prieinamas registratūroje</p>",
                            NameEng = "Luxury Room",
                            NameLT = "Liukso Kambarys",
                            PriceForAdditionalBed = 15m,
                            PriceForSecondPerson = 10m
                        },
                        new
                        {
                            ID = 9,
                            BasePrice = 55m,
                            Capacity = 0,
                            DescriptionEng = "\r\n                    Room with a stunning lake view – a perfect choice for a peaceful getaway.\r\n                    <ul>\r\n                        <li><i class='fas fa-eye'></i> Lake view</li>\r\n                        <li><i class='fas fa-wifi'></i> Free Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Breakfast available on-site</li>\r\n                        <li><i class='fas fa-car'></i> Free parking</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Tea and coffee in the room</li>\r\n                        <li><i class='fas fa-shower'></i> Spacious bathroom with shower</li>\r\n                        <li><i class='fas fa-tv'></i> Television</li>\r\n                    </ul>",
                            DescriptionLT = "\r\n                    Kambarys su nuostabiu vaizdu į ežerą – puikus pasirinkimas ramiam poilsiui.\r\n                    <ul>\r\n                        <li><i class='fas fa-eye'></i> Vaizdas į ežerą</li>\r\n                        <li><i class='fas fa-wifi'></i> Nemokamas Wi-Fi</li>\r\n                        <li><i class='fas fa-utensils'></i> Galimybė užsisakyti pusryčius vietoje</li>\r\n                        <li><i class='fas fa-car'></i> Nemokama stovėjimo vieta</li>\r\n                        <li><i class='fas fa-mug-hot'></i> Arbata ir kava kambaryje</li>\r\n                        <li><i class='fas fa-shower'></i> Erdvus vonios kambarys su dušu</li>\r\n                        <li><i class='fas fa-tv'></i> Televizorius</li>\r\n                    </ul>",
                            NameEng = "Double Room",
                            NameLT = "Dvivietis Kambarys",
                            PriceForAdditionalBed = 15m,
                            PriceForSecondPerson = 10m
                        });
                });

            modelBuilder.Entity("Centras.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Images/Room 5/Room5_1.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "Images/Room 5/Room5.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "Images/Room 5/Room5_2.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Images/Room 5/Room5_3.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "Images/Room 5/Room5_4.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "Images/Room 5/Room5_5.jfif",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "Images/Room 6/Room6_1.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "Images/Room 6/Room6_2.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "Images/Room 6/Room6_3.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "Images/Room 6/Room6_4.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "Images/Room 6/Room6_5.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "Images/Room 6/Room6_6.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "Images/Room 6/Room6_7.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "Images/Room 6/Room6_8.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "Images/Room 6/Room6_9.jfif",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "Images/Room 7/Room7_1.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "Images/Room 7/Room7.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "Images/Room 7/Room7_2.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "Images/Room 7/Room7_3.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "Images/Room 7/Room7_5.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "Images/Room 7/Room7_6.jfif",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "Images/Room 8/Room8_1.jfif",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "Images/Room 8/Room8.jpg",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "Images/Room 8/Room8_2.jfif",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "Images/Room 8/Room8_3.jfif",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "Images/Room 8/Room8_4.jfif",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "Images/Room 9/Room9_1.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "Images/Room 9/Room9_2.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "Images/Room 9/Room9_3.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "Images/Room 9/Room9_4.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "Images/Room 9/Room9_5.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "Images/Room 9/Room9_6.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "Images/Room 9/Room9_7.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "Images/Room 9/Room9_8.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "Images/Room 9/Room9_9.jfif",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "Images/Room 9/Room9_10.jfif",
                            RoomId = 9
                        });
                });

            modelBuilder.Entity("Centras.Models.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdultsNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KidsNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("Centras.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Centras.Models.RoomImage", b =>
                {
                    b.HasOne("Centras.Models.Room", null)
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Centras.Models.RoomReservation", b =>
                {
                    b.HasOne("Centras.Models.Room", "Room")
                        .WithMany("RoomReservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Centras.Models.Room", b =>
                {
                    b.Navigation("RoomImages");

                    b.Navigation("RoomReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
