//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centras.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centras.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutTitle.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalInfo.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string Checkin {
            get {
                return ResourceManager.GetString("Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmReservation.
        /// </summary>
        public static string ConfirmReservation {
            get {
                return ResourceManager.GetString("ConfirmReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desc5.
        /// </summary>
        public static string desc5 {
            get {
                return ResourceManager.GetString("desc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptionRoom5.
        /// </summary>
        public static string descriptionRoom5 {
            get {
                return ResourceManager.GetString("descriptionRoom5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptionRoom6.
        /// </summary>
        public static string descriptionRoom6 {
            get {
                return ResourceManager.GetString("descriptionRoom6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptionRoom7.
        /// </summary>
        public static string descriptionRoom7 {
            get {
                return ResourceManager.GetString("descriptionRoom7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptionRoom8.
        /// </summary>
        public static string descriptionRoom8 {
            get {
                return ResourceManager.GetString("descriptionRoom8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptionRoom9.
        /// </summary>
        public static string descriptionRoom9 {
            get {
                return ResourceManager.GetString("descriptionRoom9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrinkMenu.
        /// </summary>
        public static string DrinkMenu {
            get {
                return ResourceManager.GetString("DrinkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindRoom.
        /// </summary>
        public static string FindRoom {
            get {
                return ResourceManager.GetString("FindRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginBtn.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginEmail.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginForgotPw.
        /// </summary>
        public static string LoginForgotPw {
            get {
                return ResourceManager.GetString("LoginForgotPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginNotMember.
        /// </summary>
        public static string LoginNotMember {
            get {
                return ResourceManager.GetString("LoginNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPw.
        /// </summary>
        public static string LoginPw {
            get {
                return ResourceManager.GetString("LoginPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginRegister.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainMenu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavAboutUs.
        /// </summary>
        public static string NavAboutUs {
            get {
                return ResourceManager.GetString("NavAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavContacts.
        /// </summary>
        public static string NavContacts {
            get {
                return ResourceManager.GetString("NavContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavMenu.
        /// </summary>
        public static string NavMenu {
            get {
                return ResourceManager.GetString("NavMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavReservation.
        /// </summary>
        public static string NavReservation {
            get {
                return ResourceManager.GetString("NavReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavRooms.
        /// </summary>
        public static string NavRooms {
            get {
                return ResourceManager.GetString("NavRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PizzaMenu.
        /// </summary>
        public static string PizzaMenu {
            get {
                return ResourceManager.GetString("PizzaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal.
        /// </summary>
        public static string Postal {
            get {
                return ResourceManager.GetString("Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegBtn.
        /// </summary>
        public static string RegBtn {
            get {
                return ResourceManager.GetString("RegBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEmail.
        /// </summary>
        public static string RegEmail {
            get {
                return ResourceManager.GetString("RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegHaveAccount.
        /// </summary>
        public static string RegHaveAccount {
            get {
                return ResourceManager.GetString("RegHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegLastname.
        /// </summary>
        public static string RegLastname {
            get {
                return ResourceManager.GetString("RegLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegLogin.
        /// </summary>
        public static string RegLogin {
            get {
                return ResourceManager.GetString("RegLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegName.
        /// </summary>
        public static string RegName {
            get {
                return ResourceManager.GetString("RegName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegPw.
        /// </summary>
        public static string RegPw {
            get {
                return ResourceManager.GetString("RegPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegPw2.
        /// </summary>
        public static string RegPw2 {
            get {
                return ResourceManager.GetString("RegPw2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegTitle.
        /// </summary>
        public static string RegTitle {
            get {
                return ResourceManager.GetString("RegTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationConfirm.
        /// </summary>
        public static string ReservationConfirm {
            get {
                return ResourceManager.GetString("ReservationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationConfirmThanks.
        /// </summary>
        public static string ReservationConfirmThanks {
            get {
                return ResourceManager.GetString("ReservationConfirmThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantCenter.
        /// </summary>
        public static string RestaurantCenter {
            get {
                return ResourceManager.GetString("RestaurantCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomImages.
        /// </summary>
        public static string RoomImages {
            get {
                return ResourceManager.GetString("RoomImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomsImages.
        /// </summary>
        public static string RoomsImages {
            get {
                return ResourceManager.GetString("RoomsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SushiMenu.
        /// </summary>
        public static string SushiMenu {
            get {
                return ResourceManager.GetString("SushiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
    }
}
