//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centras.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centras.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutSlide1.
        /// </summary>
        public static string AboutSlide1 {
            get {
                return ResourceManager.GetString("AboutSlide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutSlide2.
        /// </summary>
        public static string AboutSlide2 {
            get {
                return ResourceManager.GetString("AboutSlide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutSlide3.
        /// </summary>
        public static string AboutSlide3 {
            get {
                return ResourceManager.GetString("AboutSlide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginBtn.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginEmail.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginForgotPw.
        /// </summary>
        public static string LoginForgotPw {
            get {
                return ResourceManager.GetString("LoginForgotPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginNotMember.
        /// </summary>
        public static string LoginNotMember {
            get {
                return ResourceManager.GetString("LoginNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPw.
        /// </summary>
        public static string LoginPw {
            get {
                return ResourceManager.GetString("LoginPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginRegister.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavAboutUs.
        /// </summary>
        public static string NavAboutUs {
            get {
                return ResourceManager.GetString("NavAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavContacts.
        /// </summary>
        public static string NavContacts {
            get {
                return ResourceManager.GetString("NavContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavMenu.
        /// </summary>
        public static string NavMenu {
            get {
                return ResourceManager.GetString("NavMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavRooms.
        /// </summary>
        public static string NavRooms {
            get {
                return ResourceManager.GetString("NavRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegBtn.
        /// </summary>
        public static string RegBtn {
            get {
                return ResourceManager.GetString("RegBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEmail.
        /// </summary>
        public static string RegEmail {
            get {
                return ResourceManager.GetString("RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegHaveAccount.
        /// </summary>
        public static string RegHaveAccount {
            get {
                return ResourceManager.GetString("RegHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegLastname.
        /// </summary>
        public static string RegLastname {
            get {
                return ResourceManager.GetString("RegLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegLogin.
        /// </summary>
        public static string RegLogin {
            get {
                return ResourceManager.GetString("RegLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegName.
        /// </summary>
        public static string RegName {
            get {
                return ResourceManager.GetString("RegName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegPw.
        /// </summary>
        public static string RegPw {
            get {
                return ResourceManager.GetString("RegPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegPw2.
        /// </summary>
        public static string RegPw2 {
            get {
                return ResourceManager.GetString("RegPw2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegTitle.
        /// </summary>
        public static string RegTitle {
            get {
                return ResourceManager.GetString("RegTitle", resourceCulture);
            }
        }
    }
}
